Revert "add lita-whois plugin"
This reverts commit d8964bf86ba5bb0f50ad32e9fa20bf106d4169c3.

```
INFO: Message is too long
ERROR: Lita::Handlers::Whois crashed. The exception was:
400 Bad Request
```